apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: mksclustername
  project: poc
spec:
  type: mks
  blueprint: default
  config:
    location: "clusterlocation"
    k8sVersion: "kubernetesversion"
    operating_system: "operatingsystemversion"
    autoApproveNodes: true
    defaultStorageClass: "GlusterFs"
    highAvailability: false
    dedicatedMastersEnabled: false
    storageClasses:
    - name: Local
      storagePath: "/var/openebs/local/"
    - name: GlusterFs
      storagePath: ""
    nodes:
    - hostname: nodehostname
      ipAddress: sshipaddress
      sshPrivateKeyPath: "./mks/cluster/sshkey"
      sshPort: 22
      sshUserName: ssh-user
      storageDeviceLocation: /dev/sdb
      roles:
        - Master
        - Worker
        - Storage