apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: seccomp-custom
  project: poc
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/seccomp-custom/seccomp.yaml
    options: {}
    type: Yaml
  templateName: seccomp-custom