name: Rafay SOM Provision MKS
on:
  push:
    paths:
      - 'mks/provision_mks.ps1'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./mks/provision_mks.ps1 '${{ secrets.rafaysecret }}'
